In [ ]:
import pandas as pd

#Load the data
df = pd.read_csv("../data/obesity.csv")
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,0.00,1.000,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.00,yes,no,3.0,3.0,Sometimes,yes,3.00,yes,3.00,0.000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,2.00,1.000,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.00,no,no,3.0,3.0,Sometimes,no,2.00,no,2.00,0.000,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.80,no,no,2.0,1.0,Sometimes,no,2.00,no,0.00,0.000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21,1.71,131.41,yes,yes,3.0,3.0,Sometimes,no,1.73,no,1.68,0.906,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22,1.75,133.74,yes,yes,3.0,3.0,Sometimes,no,2.01,no,1.34,0.599,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23,1.75,133.69,yes,yes,3.0,3.0,Sometimes,no,2.05,no,1.41,0.646,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24,1.74,133.35,yes,yes,3.0,3.0,Sometimes,no,2.85,no,1.14,0.586,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24,1.74,133.47,yes,yes,3.0,3.0,Sometimes,no,2.86,no,1.03,0.714,Sometimes,Public_Transportation,Obesity_Type_III

In [1]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
import joblib
#Encoding the data in machine understandable way

#Binary encoding for yes/no to 1/0
binary_features = ["family_history_with_overweight", "FAVC", "SMOKE", "SCC"]
df[binary_features] = df[binary_features].replace({"yes":1, "no":0})



df['NObeyesdad'] = df['NObeyesdad'].replace(
    {"Insufficient_Weight":0, "Normal_Weight":1,"Overweight_Level_I":2,"Overweight_Level_II":3,
     "Obesity_Type_I":4,"Obesity_Type_II":5,"Obesity_Type_III":6})

#One-Hot Encoding for categorical features
categorical_features =["Gender", "CAEC", "CALC", "MTRANS"]
encoder = OneHotEncoder(drop="first",sparse_output=False)
encoded_cats = encoder.fit_transform(df[categorical_features])
joblib.dump(encoder, "encoder.pkl") #Save the encoder

#convert encoded categories to DataFrame
encoded_cat_df = pd.DataFrame(encoded_cats,columns=encoder.get_feature_names_out(categorical_features))

#drop original categoriacla columns and merge encoded data
df = df.drop(columns=categorical_features)
df = pd.concat([df, encoded_cat_df], axis=1)

#scale the continuous features
continuous_features = ["Age", "Height", "Weight", "NCP", "CH2O", "FAF"]
scaler = StandardScaler()
df[continuous_features] = scaler.fit_transform(df[continuous_features])
joblib.dump(scaler, "scaler.pkl")

df.to_csv("../data/obesity_nice_encoded.csv")
df

NameError: name 'df' is not defined

In [ ]:
df = df.sample(frac=1).reset_index(drop=True)
df = df.sample(frac=1).reset_index(drop=True)
df.dropna()
df

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,...,CAEC_Frequently,CAEC_Sometimes,CAEC_no,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,-0.521741,2.446588,1.221081,1,1,2.00,0.404102,0,1.618701,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.207057,0.304028,-0.156809,1,1,2.71,0.211274,0,-0.780107,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,-0.521741,0.196900,1.773689,1,1,3.00,0.404102,0,-0.584286,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,-0.364399,0.411156,0.283138,1,1,2.00,0.404102,0,-0.013141,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.264970,-0.874380,0.924728,1,1,3.00,0.404102,0,1.129148,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,-0.049714,-1.088636,0.531372,1,1,3.00,-2.166941,0,-1.644983,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2107,-0.836426,1.696692,0.078059,1,1,2.05,1.471085,0,-0.600605,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2108,-0.521741,-0.124484,1.801567,1,1,3.00,0.404102,0,-1.090157,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2109,-0.993768,-0.017356,-1.317399,1,1,2.85,0.404102,0,-0.013141,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2110,-0.993768,-0.017356,-1.391105,1,1,1.76,0.404102,0,-1.400207,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

#Split the dataset
x = df.drop(columns=["NObeyesdad"])
y = df["NObeyesdad"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=500, max_depth=None, random_state=42,min_samples_split=5,min_samples_leaf=1)
model.fit(x_train, y_train)
joblib.dump(model, "model.pkl")
cv_scores_rf = cross_val_score(model, x_train, y_train, cv=5, scoring='accuracy')

print("Random Forest Mean Accuracy:", cv_scores_rf.mean())
print("Random Forest Std Dev:", cv_scores_rf.std())

Random Forest Mean Accuracy: 0.9466963987849631
Random Forest Std Dev: 0.010698850811247227

In [ ]:
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"RÂ² Score: {r2:.4f}")  # Measures how well the model fits

Mean Absolute Error (MAE): 0.0662
Mean Squared Error (MSE): 0.1466
Root Mean Squared Error (RMSE): 0.3828
RÂ² Score: 0.9640